### ISSUE TITLE
Transferring Prompt Data Between Computers

### ISSUE THREAD

**Issue by malekinho8** [LucasAschenbach/prompster#6]
Hi @LucasAschenbach,

Thank you for your excellent work on this repository, first and foremost. I have been using this extension extensively for the past few months and it has saved me a lot of time. There is just one feature that I've been wishing was added now for a while regarding prompt data transfer.

To give you some background on my attempts to resolve this:

1. **SQLite Exploration:** I've spent considerable time looking into `.sqlite` files within the local file directory, hoping to find where the data might reside.
2. **Extension Debugging:** I tried debugging the extension within Firefox to see if I could pinpoint where the data is managed.
3. **Firefox Developer Tools:** Through the Developer Tools in Firefox, I managed to discover the "Extension Storage" section. Within this storage, I found a key named `prompts` which appeared to have a dictionary as its value, containing all the prompt-message pairs I've been working with. However, I reached a dead-end after this, as I couldn't determine a method to extract, modify, or transfer this data efficiently.

Given my findings, I am mainly raising this issue because I've created something on the order of 100 prompts, and it becomes quite tedious to manually transfer this data from my main computer to my secondary ones.

Is there any possibility we could have an "export" and "import" functionality within the extension? Such a feature would be incredibly valuable, ensuring a streamlined process for backup and data migration between devices.

I completely understand the intricacies of adding new features, especially if there are underlying technical or security considerations. However, I'm eager to help! While I have some experience in coding, I'm not too familiar with TypeScript. If you could point me in the right direction, I'd be happy to try and contribute towards this feature.

Once again, thanks for all your hard work. I understand that maintaining open-source projects is a hefty task, and your dedication doesn't go unnoticed. Look forward to hearing back whenever you get a chance.

Best,
Malek

**Comment by LucasAschenbach** [comment]
Hey Malek,

thank you for the kind words. I'm glad prompster has been a helpful tool to you. As of version 1.2, prompster has an export and import function which can be accessed from the prompt explorer in the top right corner:

<img width="400" alt="Screenshot 2023-08-21 at 10 06 41" src="https://github.com/LucasAschenbach/prompster/assets/37406743/b2f33e64-1f90-4d52-ab5b-4a4d348ffe43">

On Firefox there is an issue that currently prevents the import of new prompts. The reason is that Firefox automatically closes an extension's popup window once the focus moves to another window like the file explorer. It seems many other extensions are having issues with this on Firefox: https://github.com/bitwarden/clients/issues/3013. As a temporary fix, you can disable the autohide in Firefox about:config by setting `ui.popup.disable_autohide` to true. However, this also requires you to close the popup window using escape.

So far I haven't found a satisfying solution for this. If you are up for it, try if you can find a workaround for this. I think the issue https://github.com/bitwarden/clients/issues/3013 might be a good starting point. If you have any questions, I'm happy to provide assistance. Also, even if you do not find a solution, feel free to share your findings here.

**Comment by malekinho8** [comment]
Thanks, got it working now!
