### ISSUE TITLE
Bug: Slash Commands do not work unless typed at text field beginning

### ISSUE THREAD

**Issue by infiniumparty** [LucasAschenbach/prompster#7]
Hi, when the text field is empty, slash commands work as expected. However, if there's any text in the field, these commands fail to function.

UPDATE: Initially, I believed slash commands failed when there was text in the text fields. However, upon further testing, I found that they only work when the typing cursor is positioned at the very beginning of the text field regardless of the absence or presence of text, as illustrated in the screenshot I captured. Even If I move the typing cursor with space without any text in the field it also won't work.

<img width="579" alt="image" src="https://github.com/LucasAschenbach/prompster/assets/129176265/4578806b-c31d-48f6-a597-1310c9026c20">

**Comment by LucasAschenbach** [comment]
Thanks for filing this issue!

In the last update, I have added a setting to choose whether prompster is triggered always or only when the cursor is at the beginning of an input field. You can disable this behavior under settings (three dots in the popup's search bar).

However, you are raising a valid point that this is not the expected behavior by default. I've created a new version where this setting is by default disabled.
